### ISSUE TITLE
如何判断设备是lichee rv nano

### ISSUE THREAD

**Issue by nihui** [sipeed/LicheeRV-Nano-Build#1]
```
cat /proc/device-tree/model
Cvitek. CV181X ASIC. C906.
```

名字和 milkv duo 256m 一样

**Comment by 0x754C** [comment]
最新SDK加上了model:

https://github.com/sipeed/LicheeRV-Nano-Build/tree/v4.1.0-licheervnano

https://github.com/sipeed/LicheeRV-Nano-Build/blob/328b5ad038a6f2cd73b80af3b1322ac920fed1a3/build/boards/cv181x/cv1812cp_licheerv_nano_sd/dts_riscv/cv1812cp_licheerv_nano_sd.dts#L109

```
cat /proc/device-tree/model 
LicheeRv Nano
```

**Comment by nihui** [comment]
> 最新SDK加上了model:
> 
> https://github.com/sipeed/LicheeRV-Nano-Build/tree/v4.1.0-licheervnano
> 
> https://github.com/sipeed/LicheeRV-Nano-Build/blob/328b5ad038a6f2cd73b80af3b1322ac920fed1a3/build/boards/cv181x/cv1812cp_licheerv_nano_sd/dts_riscv/cv1812cp_licheerv_nano_sd.dts#L109
> 
> ```
> cat /proc/device-tree/model 
> LicheeRv Nano
> ```

LicheeRv Nano 不是 LicheeRV Nano ？
