### ISSUE TITLE
build_all not good

### ISSUE THREAD

**Issue by F-Fichter** [sipeed/LicheeRV-Nano-Build#10]
Ok build_all and 👍🏽 
>>> qt5svg a9752b00a03438de8e5b080073816e12409404b7 Fixing libtool files
for la in $(find /DATAS/RISCV/licheeRV-nano/buildroot/output/per-package/qt5svg/host/riscv64-buildroot-linux-musl/sysroot/usr/lib* -name "*.la"); do \
	cp -a "${la}" "${la}.fixed" && \
	/usr/bin/sed -i -e "s:/DATAS/RISCV/licheeRV-nano/buildroot/output:@BASE_DIR@:g" \
		-e "s:/DATAS/RISCV/licheeRV-nano/buildroot/output/per-package/qt5svg/host/riscv64-buildroot-linux-musl/sysroot:@STAGING_DIR@:g" \
		 \
		-e "s:\(['= ]\)/usr:\\1@STAGING_DIR@/usr:g" \
		-e "s:\(['= ]\)/lib:\\1@STAGING_DIR@/lib:g" \
		 \
		-e "s:@STAGING_DIR@:/DATAS/RISCV/licheeRV-nano/buildroot/output/per-package/qt5svg/host/riscv64-buildroot-linux-musl/sysroot:g" \
		-e "s:@BASE_DIR@:/DATAS/RISCV/licheeRV-nano/buildroot/output:g" \
		"${la}.fixed" && \
	if cmp -s "${la}" "${la}.fixed"; then \
		rm -f "${la}.fixed"; \
	else \
		mv "${la}.fixed" "${la}"; \
	fi || exit 1; \
done
make[1]: Leaving directory '/DATAS/RISCV/licheeRV-nano/buildroot'
make: *** [Makefile:558: br-rootfs-pack] Error 2

**Comment by 0x754C** [comment]
can you provide your linux distro name & version?

**Comment by F-Fichter** [comment]
hello,

root@bullhomedocker:/DATAS/RISCV/licheeRV-nano# cat /etc/debian_version 
12.5

but this work fine :  https://github.com/sipeed/LicheeRV-Nano-Build/releases/tag/20240315

search for have debian.....

**Comment by adnan-aj** [comment]
On my Ubuntu 22.04, I had to install mercurial at some point during my failed build - I hope it helps you.
`sudo apt install mercurial`

**Comment by F-Fichter** [comment]
Possible to install rootfs-ubuntu with :  https://github.com/sipeed/LicheeRV-Nano-Build/releases/tag/20240315 like 

https://github.com/carlosedp/riscv-bringup/blob/master/Ubuntu-Rootfs-Guide.md because i can make ubuntu rootfs, debian no work.....

yes i have make install mercurial now i have : 
How i can clean all after a build_all ?

usr/lib/qt/examples/multimediawidgets/videographicsitem/
usr/lib/qt/examples/multimediawidgets/videographicsitem/main.cpp
usr/lib/qt/examples/multimediawidgets/videographicsitem/videographicsitem
usr/lib/qt/examples/multimediawidgets/videographicsitem/videographicsitem.pro
usr/lib/qt/examples/multimediawidgets/videographicsitem/videoplayer.cpp
usr/lib/qt/examples/multimediawidgets/videographicsitem/videoplayer.h
usr/lib/qt/examples/multimediawidgets/videowidget/
usr/lib/qt/examples/multimediawidgets/videowidget/main.cpp
usr/lib/qt/examples/multimediawidgets/videowidget/videoplayer.cpp
usr/lib/qt/examples/multimediawidgets/videowidget/videoplayer.h
usr/lib/qt/examples/multimediawidgets/videowidget/videowidget
usr/lib/qt/examples/multimediawidgets/videowidget/videowidget.pro
usr/lib/qt/plugins/
usr/lib/qt/plugins/audio/
usr/lib/qt/plugins/audio/libqtaudio_alsa.so
usr/lib/qt/plugins/mediaservice/
usr/lib/qt/plugins/mediaservice/libqtmedia_audioengine.so
usr/lib/qt/plugins/playlistformats/
usr/lib/qt/plugins/playlistformats/libqtmultimedia_m3u.so

sent 3,664,422 bytes  received 8,104 bytes  7,345,052.00 bytes/sec
total size is 3,635,260  speedup is 0.99
make[1]: Leaving directory '/DATAS/RISCV/LicheeRV-Nano-Build/buildroot'
make: *** [Makefile:558: br-rootfs-pack] Error 2

**Comment by 0x754C** [comment]
we have create a debian container, but it build failed.... need some time found reason & fix it:

https://github.com/sipeed/LicheeRV-Nano-Build/blob/main/host/debian/Dockerfile


please use ubuntu container build it:

https://github.com/sipeed/LicheeRV-Nano-Build/blob/main/host/ubuntu/Dockerfile

**Comment by F-Fichter** [comment]
ok run a ubuntu system and an ubuntu docker but  ?

fran@fran-Standard-PC-Q35-ICH9-2009:/DATAS/RISCV/LicheeRV-Nano-Build/host/ubuntu$ docker run --name licheervnano-build-ubuntu
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Create and run a new container from an image


can you correct you re cmd on this and correct you re github too  :D
