### ISSUE TITLE
mdnsd进程导致内存泄漏

### ISSUE THREAD

**Issue by arrize** [sipeed/LicheeRV-Nano-Build#12]
按照教程 用了C906的配置  build_all 编译出img之后, 用dd 命令把img 烧进tf卡(金士顿的), 
上电启动后 free 查看可用内存一直再减少,  大概5s 少0.1M, 直到内存耗光 

挨个kill 了进程后, 发现kill了 mdnsd 进程后, 泄漏终于停止了........,这个进程看起来是dns服务的守护进程,  没有用过, 不知道有没有人遇到过这个问题 
[MobaXterm_COM3SiliconLabsCP210xUSBtoUARTBridgeCOM3_20240330_020359.log](https://github.com/sipeed/LicheeRV-Nano-Build/files/14807401/MobaXterm_COM3SiliconLabsCP210xUSBtoUARTBridgeCOM3_20240330_020359.log)
具体可以看看我提供的log

还有个疑问, 我看淘宝上板子 的描述内存应该是256M, 为啥我的才150M.....

**Comment by 0x754C** [comment]
some memory use for ION,FreeRTOS,OpenSBI

mdns is disabled on new system, use avahi instead it
