### ISSUE TITLE
Reclaiming ION memory, understanding the parts of the system

### ISSUE THREAD

**Issue by znuh** [sipeed/LicheeRV-Nano-Build#15]
ION reserves approx. 30% of the whole RAM (75MB of 256MB):
_Ion: Ion memory setup at 0x000000008b300000 size 75 MiB_

As far as I understand ION is basically a memory manager for Android. If Android is not used, is ION still necessary? (Are there certain drivers that will not work without ION?)
I don't want to use Android and I would like to have more memory available in the regular Linux userspace. If ION is still needed for some drivers, can the size be reduced to less than the 75 MiB?
(I haven't found documentation regarding this so far, so if there is any documentation I'd be happy to get some pointers as well.)

In most of my potential use-cases I'll probably use the board without using the NPU, audio/video subsystem, no video input and with no video output. (Headless basically)

I also would like to understand more how all the parts of the system & boot process come into play when running in RV mode. My current understanding is:
1) Mask ROM bootloader fetches 1st stage BL and starts it
2) FSBL (first stage bootloader, part of image) starts, does the DDR3 RAM init, loads and starts RTOS
3) FreeRTOS/CVIRTOS starts, creates audio task (on E-core?)
4) secondary loader invokes OpenSBI (similar to TEE on ARM?)
5) OpenSBI does some monitor stuff, loads and invokes U-Boot
6) U-Boot comes up, loads Linux kernel & devicetree, starts Linux kernel
7) Linux kernel does its things, then invokes init from userland

So mostly I wonder what the FreeRTOS does (apart from audio?), which core it's running on and if it continues running in parallel to the normal OS.
The OpenSBI monitor probably stays active in the background as well when the regular OS comes up?

Anyway, as far as I can see RTOS and SBI don't take up much RAM compared to ION. Therefore I'd like to get rid of ION if it's not needed or at least reduce the ION size.

**Comment by 0x754C** [comment]
ION is used for multimedia, such as camera/video codec/ive

ION memory size is setup by devicetree, generate by a python script:

https://github.com/sipeed/LicheeRV-Nano-Build/blob/ecbcc0e374e1f66cd139e8673734787a01c37c88/build/boards/sg200x/sg2002_licheervnano_sd/memmap.py#L43

**Comment by 0x754C** [comment]
FreeRTOS is optional, you can disable by menuconfig
