### ISSUE TITLE
Enabling USB devices

### ISSUE THREAD

**Issue by glenn37** [sipeed/LicheeRV-Nano-Build#29]
Hi, 
I have successfully built my own firmware using the Build.
However, I do not need the RNDIS function, but I require USB storage devices (plugging in a usb flashdrive through the USB otg port).

Currently, plugging in a thumbdrive does not show anything, it is not recognised at all (with lsusb command)

What packages do I select in buildroot or kernel to enable the function and disable the RNDIS gadget?

Thanks.

**Comment by glenn37** [comment]
你好，
我已经成功建了自己的固件。
但是，我不需要RNDIS功能，但我需要USB存储设备（通过USB otg 插入USB闪盘）。

目前，插入闪盘不会显示任何内容，根本无法识别（使用 lsusb 命令）

我应该在 buildroot 或内核中选择哪些软件包来启用该功能并禁用 RNDIS 小工具？

谢谢。

**Comment by taorye** [comment]
Removing /boot/usb.rndis will disable the RNDIS function. Check the `/etc/init.d/S03usbdev` file, as it actually controls the gadget function.

**Comment by Neutree** [comment]
remove /boot/usb.device and create /boot/usb.host, then reboot
