### ISSUE TITLE
How to ssh to device?

### ISSUE THREAD

**Issue by MatejKovacic** [sipeed/LicheeRV-Nano-Build#48]
I have bought `Lichee RV Nano B` and installed image `2024-09-05-16-34-752683.img.xz` on SD card.

I have Ubuntu 24.04.1 on my laptop. When I insert SD card in `Lichee RV Nano B`, it boots, and then I see in my Ubuntu that new USB device is found (I am using `dmesg -w` command), and `lsusb` shows `Bus 005 Device 020: ID 359f:2120 sipeed licheervnano`.

If I write `ip a` command, I can see two new network interfaces:

```
32: enxb217a9652239: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether b2:17:a9:65:22:39 brd ff:ff:ff:ff:ff:ff
    inet 10.162.226.100/24 brd 10.162.226.255 scope global dynamic noprefixroute enxb217a9652239
       valid_lft 863941sec preferred_lft 863941sec
    inet6 fe80::cbda:4e37:7174:a84d/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
33: enx7eacccd77e6e: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 7e:ac:cc:d7:7e:6e brd ff:ff:ff:ff:ff:ff
    inet 10.162.225.100/24 brd 10.162.225.255 scope global dynamic noprefixroute enx7eacccd77e6e
       valid_lft 863935sec preferred_lft 863935sec
    inet6 fe80::2c7a:e10b:fdb1:3229/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

So I have `enxb217a9652239` with IP address `10.162.226.100` **and** `enx7eacccd77e6e` with IP address `10.162.225.100`. I try to SSH into `Lichee RV Nano B`:
- ssh `root@10.162.225.100`
- ssh `root@10.162.225.100`
In both cases ssh shows ED25519 key fingerprint, but I don't know the password. Official documentation states it should be `licheepi`, here I read it should be `root`, but neither of them works.

**So... how to SSH to the device?**

**Comment by Neutree** [comment]
ssh root@10.162.225.1  password is root
