### ISSUE TITLE
LED diode

### ISSUE THREAD

**Issue by MatejKovacic** [sipeed/LicheeRV-Nano-Build#54]
How can I control user LED diode?

**Comment by Neutree** [comment]
```
echo none > /sys/class/leds/led-user/trigger
echo 1 > /sys/class/leds/led-user/brightness
echo 0 > /sys/class/leds/led-user/brightness
```

and you can find control code in MaixPy also at https://github.com/sipeed/MaixCDK/blob/main/components/peripheral/port/maixcam/maix_gpio.cpp

**Comment by MatejKovacic** [comment]
OK, unfortunately I do not see it.

```
sudo ls /sys/class/leds/
:heartbeat  mmc0::  mmc1::
```

But I am using https://github.com/Fishwaldo/sophgo-sg200x-debian/, it seems it is not implemented there. How can I do it by myself?

**Comment by MatejKovacic** [comment]
Also, how can I access GPIO's (read and write), do you have any example? Because it could be possible to solder my own LED to GPIO, or to use pins for sensors...

**Comment by MatejKovacic** [comment]
Also, is it possible to connect 0.96" OLED Display Module? The one that uses SCL and SDA connectors, for instance this one: https://vi.aliexpress.com/item/1005006365881525.html
