### ISSUE TITLE
LicheeRV Nano Image Wifi Reset

### ISSUE THREAD

**Issue by muei** [sipeed/LicheeRV-Nano-Build#6]
硬件: LicheeRV Nano
镜像: https://github.com/sipeed/LicheeRV-Nano-Build/releases/download/20240124/licheervnano-20230124.img.xz

问题:
修改了`/etc/wpa_supplicant.conf`中的wifi配置, 执行命令`wpa_supplicant -i wlan0 -c /etc/wpa_supplicant.conf` 会导致wlan0丢失,
重启设备`/etc/wpa_supplicant.conf`文件会重置原样

找到原因是`/etc/rc.local`中的`/opt/stress-test/stress-test-all.sh &`脚本中，有相关wifi test的脚本，注释后可不重置，但是同样出现
执行命令`wpa_supplicant -i wlan0 -c /etc/wpa_supplicant.conf` 会导致wlan0丢失

**Comment by 0x754C** [comment]
可以提供一下dmesg日志吗?

**Comment by muei** [comment]
这个镜像不要用，用最新的就好了， 比如licheervnano-20240206-0802.img.lz4
