### ISSUE TITLE
st7789 spi lcd 

### ISSUE THREAD

**Issue by Cpasjuste** [sipeed/LicheeRV-Nano-Build#60]
Hi,

I did saw the commit to add spi lcd (st7789) support. I'm new to dts and such and i'm unable to make it work. I'm not sure how it should be wired, i tried via spi1 and spi2, messing with the dts/uboot and enabling fbtft/st7789 in kernel without success (no "/dev/fbx" device in any case).

Do someone have some direction to make it work ? Does it currently require a "mipi" screen ?

Thanks,
cpasjuste

**Comment by Cpasjuste** [comment]
Closing because sipeed doesn't seems to provide any support to it's boards.

**Comment by Neutree** [comment]
https://wiki.sipeed.com/maixpy/doc/en/modules/spilcd.html
