### ISSUE TITLE
USB RNDIS function not working

### ISSUE THREAD

**Issue by fkcheung** [sipeed/LicheeRV-Nano-Build#65]
I tried to build an image using Ubuntu by following the instructions without changing any settings, but I can't connect to the LicheeRV Nano board using the image that was built. Is there anything I missed that might prevent it from working?

**Comment by makinbacon21** [comment]
Same issue here

**Comment by makinbacon21** [comment]
checked out bd92529ed83a1a061159d6b27e7902d51d249e96 and it's working. must be a regression, prolly in the gadget init stuff.

**Comment by Neutree** [comment]
fixed https://github.com/sipeed/LicheeRV-Nano-Build/commit/fae0437895d09bdcd7b9f106e33606c64c1f01fd
