### ISSUE TITLE
Which cameras supported "out of box"?

### ISSUE THREAD

**Issue by ret7020** [sipeed/LicheeRV-Nano-Build#69]
I successfully run GC4653 camera with 70415 board.
Do I correctly understand that default image can work with this list of chips:
```
CONFIG_SENSOR_GCORE_GC4653=y
CONFIG_SENSOR_OV_OV2685=y
CONFIG_SENSOR_OV_OS04A10=y
CONFIG_SENSOR_LONTIUM_LT6911=y
CONFIG_SENSOR_SMS_SC035GS=y
```
But, can you recommend some camera modules, that tested with board? 
I saw that the board should support 22 pin csi cameras for RPI, but I did not understand what camera models are being used.

**Comment by Neutree** [comment]
GC4653 and os04a10, out of box version board: https://wiki.sipeed.com/hardware/en/maixcam/maixcam_pro.html
