### ISSUE TITLE
root password ?

### ISSUE THREAD

**Issue by F-Fichter** [sipeed/LicheeRV-Nano-Build#7]
Hello, i try the sd, with linux see the interface with USB and can have ssh, but where is the root password PLEASE ?

**Comment by F-Fichter** [comment]
root 
cvitek

   no work !

**Comment by F-Fichter** [comment]
strange software...

**Comment by KamranArain** [comment]
> Hello, i try the sd, with linux see the interface with USB and can have ssh, but where is the root password PLEASE ?

did you found the root password, I am trying the `licheepi` but it is not working.

**Comment by KamranArain** [comment]
> > Hello, i try the sd, with linux see the interface with USB and can have ssh, but where is the root password PLEASE ?
> 
> did you found the root password, I am trying the `licheepi` but it is not working.

Got it, It's 
User: `root`
Pass: `root`
